#ifdef WINLOGONNOTIFICATION_EXPORTS
#define WINLOGONNOTIFICATION_API __declspec(dllexport)
#else
#define WINLOGONNOTIFICATION_API __declspec(dllimport)
#endif

#include "WinWlx.h"


//void WINLOGONNOTIFICATION_API GetLoggedUserName(LPTSTR a_pName, DWORD a_dwMaxLength);



VOID WINLOGONNOTIFICATION_API LogonEventHandler(PWLX_NOTIFICATION_INFO pInfo);
VOID WINLOGONNOTIFICATION_API LogoffEventHandler(PWLX_NOTIFICATION_INFO pInfo);
VOID WINLOGONNOTIFICATION_API LockEventHandler(PWLX_NOTIFICATION_INFO pInfo);
VOID WINLOGONNOTIFICATION_API UnLockEventHandler(PWLX_NOTIFICATION_INFO pInfo);
VOID WINLOGONNOTIFICATION_API ReconnectEventHandler(PWLX_NOTIFICATION_INFO pInfo);
VOID WINLOGONNOTIFICATION_API DisconnectEventHandler(PWLX_NOTIFICATION_INFO pInfo);
